// User
export const TOGGLE_USER_LOGGED_IN = 'TOGGLE_USER_LOGGED_IN';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';

// Fields
export const TOGGLE_SHOW_UPDATE_FIELD_MODAL = 'TOGGLE_SHOW_UPDATE_FIELD_MODAL';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const INIT_FIELDS = 'INIT_FIELDS';
